config/routes.rb
RailsStripeApp::Application.routes.draw do

  match '/new',     to: 'deals#new_deal'

  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/help',    to: 'static_pages#help'
  match '/pricing',    to: 'static_pages#pricing'

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end

  mount StripeEvent::Engine => 'http://localhost:3000/stripe' # provide a custom path
  resources :users
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer">
    <small><%= link_to "my app", root_path, :class => 'brand' %></small>
    <p>© Copyright 2013. All rights reserved.</p>
    <nav>
      <ul class="inline nav">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Help & support", help_path %></li>
       </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top ">
  <nav class="navbar-inner">

      <%= link_to "my app", root_path, :class => 'brand' %>
      <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
          <li><%= link_to "Creat a new Deals", new_path %></li>
          <li><%= link_to "Deals", new_user_session_path %></li>

          <%else%>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to "Help & support", help_path %></li>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>

        <% if user_signed_in? %>
          <li><%= link_to 'Edit account', edit_user_registration_path %></li>
          <% if current_user.has_role? :admin %>
            <li><%= link_to 'Admin', users_path %></li>
          <% end %>
        <% end %>
      </ul>
    
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- LayerSlider styles -->
    <link rel="stylesheet" href="/layerslider/css/layerslider.css" type="text/css">

    <!-- jQuery with jQuery Easing, and jQuery Transit JS -->
    <script src="/layerslider/jQuery/jquery.js" type="text/javascript"></script>
    <script src="/layerslider/jQuery/jquery-easing-1.3.js" type="text/javascript"></script>
    <script src="/layerslider/jQuery/jquery-transit-modified.js" type="text/javascript"></script>

    <!-- LayerSlider from Kreatura Media with Transactions -->
    <script src="/layerslider/js/layerslider.transitions.js" type="text/javascript"></script> 
    <script src="/layerslider/js/layerslider.kreaturamedia.jquery.js" type="text/javascript"></script> 
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Stripe App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Stripe App" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <%= render 'layouts/shim' %> 
  </head>

  <body>
    <div id="wrapper">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div> <!--! end of #container -->
  </body>
</html>